baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: $PRIMARY_SITE_NAME
primary: true
siteGroup: 4ce8fce1-9127-4152-be2a-d5cd1a3db080 # mattwilliams-ux
sortOrder: 1
