enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  e95e98ad-f5f5-4336-8cf9-a4826910cc6d: # $PRIMARY_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: home/_entry
    uriFormat: __home__
type: single
