dateModified: 1615399989
email:
  fromEmail: $EMAIL_ADDRESS
  fromName: $EMAIL_ADDRESS
  replyToEmail: null
  template: null
  transportSettings:
    password: $EMAIL_PASSWORD
    timeout: '10'
    username: $EMAIL_USER
  transportType: craft\mail\transportadapters\Gmail
system:
  edition: solo
  live: true
  name: $PRIMARY_SITE_NAME
  retryDuration: null
  schemaVersion: 3.6.6
  timeZone: America/New_York
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
